### ISSUE TITLE
add support to add shared_preload_libraries list in chart

### ISSUE THREAD

**Issue by kirankumar-grootan** [cloudnative-pg/charts#314] opened 2024-06-12 10:24 UTC
add support to add shared library instead of hardcoded time timescaledb lib alone
https://github.com/cloudnative-pg/charts/blob/main/charts/cluster/templates/cluster.yaml#L51

**Comment by kirankumar-grootan** [comment] 2024-06-12 10:31
```
   shared_preload_libraries:
      {{- if eq .Values.type "timescaledb" }}
      - timescaledb
      {{- end }}
      {{- with .Values.cluster.postgresql.shared_preload_libraries }}
      {{ . | indent 6}}
      {{- end }}
    parameters: {{- toYaml .Values.cluster.postgresql.parameters | nindent 6 }}
```
we can change something like this

**Comment by itay-grudev** [comment] 2024-06-13 08:29
Duplicate of #278, which I closed as I'm not sure I want to do this.

That being said, what is your use case? Change my mind.

**Comment by kirankumar-grootan** [comment] 2024-06-25 09:25
Hi @itay-grudev

Thank you for looking into this ticket. I'm closing this issue. We previously deployed PostgreSQL using the default PostgreSQL image from Docker Hub, which required manual installation of the `pg_stat_statements` extension to retrieve query time. However, with the CloudNative PG image, this functionality is included by default, allowing us to obtain query time information without any additional steps.

**Comment by cterence** [comment] 2024-07-22 22:18
Hi @itay-grudev , sorry to comment on a closed issue but I would like to push for this feature to be added to the chart.
My use case is simple : deploy a CNPG Cluster for [immich](https://github.com/immich-app/immich-charts). It depends on the pgvectors extension which fortunately has its own [CNPG docker image](https://github.com/tensorchord/cloudnative-pgvecto.rs).
However, I cannot use it with this chart as I have to modify the `shared_preload_libraries` parameter.
Being able to change this value would be beneficial for this chart and would encourage the development of these kinds of Docker images.

**Comment by 11qu1d** [comment] 2024-08-17 13:37
Yeah, just stumbled upon the same issue. Would be great to have this covered by the charts.

**Closed** 2024-09-09 12:16 UTC
Labels: chart( cluster )
