### ISSUE TITLE
feat(cluster): Allow the use of existing secrets for DB access (i.e. cluster-app and cluster-superuser)

### ISSUE THREAD

**Issue by mrclrchtr** [cloudnative-pg/charts#245] opened 2024-04-03 11:20 UTC
I would prefer to annotate the generated secret to be able to replicate it, but I don't think that's possible with CNPG yet, is it?

Therefore it would be very good to have the possibility to use already existing secrets for the creation of clusters.

**Comment by itay-grudev** [comment] 2024-04-08 21:10
Is this not a duplicate of #197?

There is a PR for it - #239.

**Comment by mrclrchtr** [comment] 2024-04-08 22:27
No, sorry, I should have expressed myself better. This is about using existing secrets for database access, i.e. `cluster-app` and `cluster-superuser`.

**Comment by itay-grudev** [comment] 2024-04-08 22:52
This is indeed supported by CNPG, see the `secret` parameter [here](https://cloudnative-pg.io/documentation/current/cloudnative-pg.v1/#postgresql-cnpg-io-v1-BootstrapInitDB) and `superuserSecret` [here](https://cloudnative-pg.io/documentation/current/cloudnative-pg.v1/#postgresql-cnpg-io-v1-ClusterSpec).

That being said, I'm not sure that's such a good idea. What is your use case?

**Comment by mrclrchtr** [comment] 2024-04-09 07:27
No, I didn't mean simply creating one, but annotating the generated one with the help of a template. Then it can be copied by other tools like replicator.

The idea was to run the cluster in a different namespace than the application. 

In the meantime, however, I have also decided against this. So it's probably ok to close the issue, unless you see some use in the feature?

**Comment by itay-grudev** [comment] 2024-04-09 13:47
You can use the cluster chart with your favourite orchestration tool and set the access passwords during creation time. Your orchestration tool can then allocate a secret with the credentials in your namespace.

Also I imagine you can use HashiCorp Vault for an even fancier solution.

**Closed** 2024-04-09 13:47 UTC
